### PR TITLE
added help tab

### PR DESCRIPTION
**Pull request by Gkrumbach07**
## Related Issues and Dependencies
https://github.com/thoth-station/help/issues/3

## This introduces a breaking change

- [X] No

## This Pull Request implements

Adds a new tab pointing to the help page

## Description

updated index.html

### CODE REVIEW

**Comment by codificat** [comment]
I suggest we
/hold
this until the help page has some content.

Right now it has a "Contribute to this page" button, which apparently does nothing, and a link at the top about "Documentation" that results on a 404

**Comment by codificat** [comment]
The [help page](https://thoth-station.ninja/help/) looks much better now, thanks!

However, before uholding, a couple of questions/suggestions:

- The documentation page within the help page is quite different from what you get from the home page's documentation tab. I believe they should be similar, or it should be more clear what is what. At the very least, the "main" documentation should not get "hidden" from a help page, I think.
- There is no link back to the home page in the header. What about replacing the top left icon/link with a link back home?

**Comment by Gkrumbach07** [comment]
> The documentation page within the help page is quite different from what you get from the home page's documentation tab. I believe they should be similar, or it should be more clear what is what. At the very least, the "main" documentation should not get "hidden" from a help page, I think.

We are still planning the navigation. If you have opinions, I suggest you add comments to this [doc](https://docs.google.com/document/d/1jOseHTISxTyRKnngAEnyGACuCdqWKIUdrpPrQABQBrw/edit#). Do you think the documentation tab should have all docs? Or just the docs from core repo? It can have both but I want to avoid duplication where I can, but refactoring and duplication may be necessary for consistency.

> What about replacing the top left icon/link with a link back home?

I would like to keep that icon pointing back to the help home page, otherwise there is no way to get back to it. I can however make the icon on the homepage link back to the main page and also add links back to it as well.

**Comment by codificat** [comment]
> >  What about replacing the top left icon/link with a link back home?
> 
> I would like to keep that icon pointing back to the help home page, otherwise there is no way to get back to it.

Hmmm... once this PR merges, there will be a direct link to the help page in the top navigation bar in the main website, right?

**Comment by Gkrumbach07** [comment]
> Hmmm... once this PR merges, there will be a direct link to the help page in the top navigation bar in the main website, right?

Yes. I will also make the Help page's Thoth Icon link back to the main Thoth page, but add a tab that allows a user to get back to the home page of Help

**Comment by Gkrumbach07** [comment]
@codificat I updated the Help site to link back to the home page and added a footer like to Thoth's. Let me know if this works.

**Comment by codificat** [comment]
> @codificat I updated the Help site to link back to the home page and added a footer like to Thoth's. Let me know if this works.

It is looking much better, thanks!

However, as mentioned during a recent scrum, we should wait to merge this PR (and therefore enable the link/tab) until the new help sub-site reaches a "good" state, with main issues addressed and without "conflicts" with the main website.

Some pending things:
- [ ] the discrepancy between the *Documentation" link in the main page vs the help page is still a concern: they contain different content, which is confusing.
- [ ] https://github.com/thoth-station/help/issues/18

There might be a few more nits. Rather than documenting all of this in this PR, though, these will be addressed via issues in the `help` repo and/or reviews of the site. For now, keeping this PR on hold.

**Comment by Gkrumbach07** [comment]
@codificat Changes have been made to the help page. Are there any issues that need to be resolved before this PR is merged?

**Comment by codificat** [comment]
Thanks for all the updates, to me it looks good to be merged now.
/approve

**Comment by codificat** [comment]
hmmm... it did not catch the
/approve

**Pull request merged**
